<?php


namespace Tests\Unit\Usescases;


use App\Usescases\Product\ImportCsvProductsUsecase;

use App\Utilities\Contract\ImportFileInterface;
use SplFileInfo;
use SplFileObject;
use Tests\TestCase;

class ImportCsvProductsUsescasesTest extends TestCase
{

    /**
     * @var ImportFileInterface|\Mockery\MockInterface|ImportFileInterface
     */
    private $importFile;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->importFile = \Mockery::mock(ImportFileInterface::class);


    }


    public function test_import_file()
    {
        $local_file = public_path('productos.csv');
        chmod($local_file, 777);
        $file = new SplFileObject($local_file);
        $this->importFile->shouldReceive('file')->with($file);
        $usecase = new ImportCsvProductsUsecase();

        $result = $usecase->handle($file);

        $this->assertEquals(true, $result);
    }


}